### ISSUE TITLE
open activity feed entries in browser

### ISSUE THREAD

**Issue by badboy** [EddieRingle/hubroid#14]
there should be away to open the links in activity feed entries in the browser.

issue entries make no sense if you can't even get to the website to read them and the comments.

**Comment by EddieRingle** [comment]
Yeah, I'm working on a way to tie the activity feeds in with the rest of the app, stay tuned.

**Comment by badboy** [comment]
Great!

**Comment by EddieRingle** [comment]
As of 2.0 the activity feed has internal links that link off to the rest of the app.
