### ISSUE TITLE
App crashes after doing anything with issues

### ISSUE THREAD

**Issue by davejlong** [EddieRingle/hubroid#16]
the app crashes after doing anything with issues.  New issue, comment on am issue.  everything is saved so it happens after posting to GitHub.  HTC Aria Android 2.1

**Comment by EddieRingle** [comment]
Yes, I've encountered this one before. It should be fixed after I finish refactoring for 2.0 (almost all of the app will be rewritten).

**Comment by davejlong** [comment]
Is there a date we can expect the launch?  I love using Hubroid.

**Comment by EddieRingle** [comment]
Glad you love it. :)

Well, I was in the middle of the refactor, when I suddenly decided to go a completely different way with it (to adhere to the new Android UI Guidelines better). Unfortunately I can't give a release date just yet, but I have a large gap of free time on my hands so hopefully I can make some progress on it.

**Comment by EddieRingle** [comment]
Fixed in 2.0
