### ISSUE TITLE
Always crashes when trying to open 'Recent Commits'

### ISSUE THREAD

**Issue by hjoest** [EddieRingle/hubroid#21]
Regardless of the project I choose, when I try to open 'Recent Commits' on it, Hubroid crashes.
Platform: Motorola Milestone, Android 2.1

**Comment by hjoest** [comment]
Surprisingly, after I submitted this issue a few minutes ago, I can now see the Recent Commits for eddieringle/hubroid, but still not for any other project on github.

**Comment by hjoest** [comment]
I'm using Hubroid version 1.3.2.

**Comment by EddieRingle** [comment]
1.3.2 does not support GitHub's new API changes, so I'd be surprised if anything worked at all.

2.0 will be out soon. :-)
