### ISSUE TITLE
User profile incomplete in landscape mode

### ISSUE THREAD

**Issue by ge0rg** [EddieRingle/hubroid#3]
When viewed in Landscape mode on a G1, the profile buttons are below the screen.
With a custom landscape layout, they could be placed beneath each other or to the right of the user info to take less vertical space.

**Comment by EddieRingle** [comment]
Make the user info screen scrollable in landscape mode. Closed by aa7b30c7b7dc784bd0bbee827a4db16d317d06d3.

Signed-off-by: Eddie Ringle eddie@eringle.net
