### ISSUE TITLE
Login Issues

### ISSUE THREAD

**Issue by james-kenny** [EddieRingle/hubroid#36]
Hi,

It keeps giving me an incorrect username / password. Double checked username password and everything seems fine can get onto Git Hub no problems.

**Comment by EddieRingle** [comment]
Try something for me.

Go to your browser and type in the following URL:
https://username:password@github.com/api/v2/json/user/show

Replace 'username' and 'password' above with your GitHub username (remember, not your email) and password. You'll either get back an error (if your login details are incorrect) or a bunch of information about your account on GitHub.

**Comment by james-kenny** [comment]
ok, Tried that. on my phone I got "Could not download this content" 

But I tried it out of interest on my browser on two different machines and it gave me ""error":"not authorized"" I've double checked the username/password and I'm using the right one. I've logged out and logged into github no problems.

**Comment by EddieRingle** [comment]
Hmm, maybe your password contains some characters that the API doesn't like? If it's got some out-of-the-ordinary symbols in it (though I'm not sure if this would cause this problem, I use symbols in my password and it works fine), try changing to a simple password like 'rosebud' or something for the purpose of testing it.

**Comment by james-kenny** [comment]
Ya I tried that, I had a password that had symbols etc orginally thought it was the issue so changed it to something simple and still no joy, I've sent an issue to github so will see if they can shed any light on it. 

Thanks guess it's just my luck.

**Comment by EddieRingle** [comment]
Sorry to hear that. Let me know what GitHub says, I'm interested to know. After all, I would hate for it to be a problem with Hubroid that only a select few experience.

**Comment by james-kenny** [comment]
Looks like that wasn't a problem I had to append https://username:password@github.com/api/v2/json/user/show with my username, which works from browser but from the phone i get content can't be downloaded. It's a Samsung galaxy.

**Comment by EddieRingle** [comment]
That URL will return your full user account information IF you are authenticated. It shouldn't need a username appended. What you're seeing is the public user information available to everyone (which does not include things like plan information and disk space available on your account).

**Comment by taq** [comment]
I also can't login. I tried to remove special chars on my password and just use chars and numbers and still do not works. :-(
One thing I notice is that when trying to log in on Github with my browser, it gives me an invalid certificate warning. I'm using a Galaxy 5 with Android 2.1.

**Comment by EddieRingle** [comment]
Yes, I just recently figured out that the login issues only occur on pre-Froyo devices. I have already fixed the issue as of 50ddcc7c8a6adac714c082750a0fd00c3d79475f.

A fixed version will be pushed to the Market soon, but I'd like to get a couple other tweaks in before then.

**Comment by james-kenny** [comment]
Hey, I updated this morning to the latest version and it's now working.

Thanks, oh and very nice app,

**Comment by taq** [comment]
Hey Eddie, thanks, already updated and already working! Nice app!
