### ISSUE TITLE
Diff lines should act as blocks, not as inline elements

### ISSUE THREAD

**Issue by txus** [EddieRingle/hubroid#37]
In a CSS sense :)

Here's a screenshot of a [vertical layout](http://cl.ly/2D2B3V3Y302R1H0e3L22.jpg) (everything seems ok).

But when you turn the cellphone and the [horizontal layout](http://cl.ly/0P3j2p0L2m0D133n1d3V.jpg) is set, the diff lines are set one next to the other.

**Comment by EddieRingle** [comment]
Force each diff line to its own line; Closed by d2aa1a0e3c258e269dc50b04d8ab6316b0ce32e0.

Signed-off-by: Eddie Ringle &lt;eddie@eringle.net&gt;

**Comment by txus** [comment]
LOL that was _fast_ :)

**Comment by EddieRingle** [comment]
Thanks for the heads up. The fix wasn't specifying it as a block element (as that causes some wonky highlighting glitches), but just to float and clear each line.

**Comment by EddieRingle** [comment]
And yeah, it's Sunday. I've got nothing better to do than fix stuff. ;)
