### ISSUE TITLE
File viewer: End of line symbols/identation don't work well

### ISSUE THREAD

**Issue by txus** [EddieRingle/hubroid#38]
You can see it in [this screenshot](http://cl.ly/0T2l2o3W39320T2W1G3L.jpg). The final `end` statements don't seem to render the `\n` they should afterwards.

**Comment by EddieRingle** [comment]
Force each line in FileViewer to its own line; Closed by 66dbe2d582454fbb9ddf91b32ad473128a272459.

Similar to d2aa1a0e3c258e269dc50b04d8ab6316b0ce32e0.

Signed-off-by: Eddie Ringle &lt;eddie@eringle.net&gt;

**Comment by EddieRingle** [comment]
Same fix as the diffs. :)
