### ISSUE TITLE
Gist view in the News feed

### ISSUE THREAD

**Issue by txus** [EddieRingle/hubroid#39]
It would be nice to have a bit of a gist view whenever someone "creates a gist" or "updates a gist".

**Comment by EddieRingle** [comment]
I think for now (until the API is expanded), I will place a URL in the activity view so that you can see the Gist in the browser via GitHub's site.

**Comment by EddieRingle** [comment]
Fixed by 1fb54a65b4e06bf9f51cdaaed865f8aaa2ec1970.

**Comment by txus** [comment]
Cool!
