### ISSUE TITLE
Preview comments in the News feed

### ISSUE THREAD

**Issue by txus** [EddieRingle/hubroid#40]
Whenever someone "comments on a commit", the event message is just for example:

`spastorino commented on d00ed5af`.

It would be great if just below that there was the comment itself.

**Comment by EddieRingle** [comment]
Yeah, unfortunately GitHub's API currently does not support this. :(

However, I've spoken with technoweenie and he mentioned plans for a new Events API in the next version of the API.

**Comment by txus** [comment]
Cool! :)

**Comment by EddieRingle** [comment]
@txus Just updating this. Technoweenie has given me a sneek preview of sorts to the upcoming Events API. I'll play around with it and see if I can knock this issue out.
