### ISSUE TITLE
My Gists page

### ISSUE THREAD

**Issue by txus** [EddieRingle/hubroid#41]
A nice feature to have in the future!

Does it deserve to be at the same level as 'My repositories'?

(I've seen that by now you only can list a user's public gists though)

**Comment by EddieRingle** [comment]
Yeah, the API for Gists is currently pretty limited. I plan on waiting for it to expand before I implement any real Gist functionality into Hubroid.

**Comment by dougaitken** [comment]
the new API v3 was annouced to with Gist support so will this be coming soon?

**Comment by EddieRingle** [comment]
Yes, I've been a bit busy with school and a game for Android (which I'll hopefully make some money with) lately, but I intend to implement Gist support now that a proper API is available.

**Comment by dougaitken** [comment]
Yea no worries dude, I wasn't meaning it as "its available, get on it!" kinda thing hah :)

**Comment by EddieRingle** [comment]
Just noting some progress here, I'm currently working on adding in Gist support. Still working out some kinks with Starred Gists though, so it's not quite ready for release.

**Comment by EddieRingle** [comment]
@dougaitken Considering you're still interested, the feature-gists branch contains my work on implementing Gists via the v3 API. If things go as planned, I'll also be able to implement commenting on gists, creating new ones, and updating existing gists. Currently, it is possible to viewed the currently logged in user's public/private gists as well as starred gists. It is also possible to view other user's public gists. In addition, the current code enables basic viewing of gists' files' contents.
