### ISSUE TITLE
Time offset/errors maybe du to different timezone in news feed

### ISSUE THREAD

**Issue by cyrilmhansen** [EddieRingle/hubroid#42]
Hi,

I just started contributing to a project, whose leader is in Japan, and I am from western Europe.

In github site news feed page, let's say the person in japan commited something 4 hours ago.

If i open the news feed in hubroid, i read that the commit was 12 hours ago. The 8 hours difference looks to me as the offset due to the different timezones.

**Comment by EddieRingle** [comment]
GitHub converts all timestamps to the Pacific timezone via the API, so it's definitely not server-side. I've also tried changing timezones on my device, but all of the times are consistent, no matter which timezone I'm using. If you're comparing what Hubroid reads versus what your desktop reads, maybe something is up with your desktop timezone?

**Comment by cyrilmhansen** [comment]
I tried to change the timezone in my device (keeping the same UTC time) - and it changes the display of hubroid new section. going west make the history go back in time. Ex : 8 hours ago becomes 3 hours ago for the same item.

sorry i clicked on the wrong button, for me the issue is still open

My versions : 
hubroid 2.0-beta3
android 2.2 2.6.29 (acer liquid custom rom t&l Gingerbread.14 theme)
