### ISSUE TITLE
Pushable tab stays empty

### ISSUE THREAD

**Issue by HelgePlaschke** [EddieRingle/hubroid#45]
Hi,
I am not able to see any repository (private or public) which I have write access to in the pushable tab. Even a logout or reinstallation of Hubroid didn't solve this.
Is it my fault (did I miss an option) or a bug?

**Comment by EddieRingle** [comment]
You won't see your own repositories in the pushable tab, is this what you are referring to?

**Comment by HelgePlaschke** [comment]
Yes you got it right :).

**Comment by EddieRingle** [comment]
Right, you shouldn't be able to. In fact, the Pushable tab should be removed from view if no other user has given you push access to any of their repositories.

**Comment by HelgePlaschke** [comment]
But shouldn't my private repositories then at least be shown in the repositories tab?
The current version only displays me my public repositories, watched repositories and repositories I have push access to which I don't own. So at least in one of those tabs I think my private repos should be displayed :).

**Comment by EddieRingle** [comment]
The primary Repositories tab does show private repositories.

**Comment by HelgePlaschke** [comment]
Hmm could there be an old config or something like that? My repositories tab just shows me my public repos, my private ones don't show up there :( [Hubroid > Repositories > Repositories right?].

**Comment by EddieRingle** [comment]
Hmm, that's really odd. I honestly don't know what to tell you. I can see all of my private repositories fine in the Repositories tab. Are you having problems with any other part of the app (like creating/commenting on an issue, perhaps)?

**Comment by EddieRingle** [comment]
@HelgePlaschke Are you still encountering this issue?

**Comment by EddieRingle** [comment]
Closing this as it works as intended for me.
