### ISSUE TITLE
Improve flow for common use cases

### ISSUE THREAD

**Issue by sblom** [EddieRingle/hubroid#46]
Today, when I launch the application, I'm not presented with anything of interest. Most commonly, I'll click "News Feed" as a starting point. But the application could launch the news feed by default, so that I have an interesting experience in zero clicks. There could be icons (or tabs?) along the top or bottom to choose Profile, Repos, or Users. I'm not a very good visual designer so I'm not sure what it should look like, but I'm sure that the launch experience should provide _some_ experience in zero clicks.

My second most common use case is to find out what changes were recently committed to a repository that I collaborate on. To get there, I have to click Repositories->Pushable->RepoName->Branches->Master->Commit Log. That's 6 clicks. I don't know if there's a way to get it down to 2 clicks, but I'm sure we can improve on 6 clicks.

One approach might be to merge "Pushable" and "Mine" into one list much like github.com does. Or even put one set at the top of the list and put the second set below the first in the same list. Once I choose a repo, in the same vein as news on the main page, the history for the master branch could be the default view, and other things might be tabs or buttons from there.

**Comment by EddieRingle** [comment]
Thanks for your comments.

I modeled 2.0 after Google's Design Patterns, so the Dashboard is a result of that. However, I believe a nice feature addition would be to enable setting one of the Dashboard options as default and launch to that screen immediately when the app starts.

As for improving the clicks to reaching commit logs, I've yet to add long-press actions to lists, so improvements will probably appear in that area soon.

**Comment by EddieRingle** [comment]
@sblom I've split this issue in two to better keep track of individual features. See Issues #61 and #62.
