### ISSUE TITLE
Commit timings not in sync with local device time

### ISSUE THREAD

**Issue by pierskarsenbarg** [EddieRingle/hubroid#47]
When I look at my commit logs it always adds approximately 7 hours onto the commit time message ("x hours ago"). Presumably this is because it is taking the time from the github servers, but would it be possible to correct this time according to the local device?

**Comment by EddieRingle** [comment]
I'm not sure why this is occurring for some people. The times display fine for me, and I'm in a different timezone than GitHub as well. Even if I set my phone to a different timezone, such as one in Europe, everything still works out. I'll have to look into this further.

**Comment by pierskarsenbarg** [comment]
If it helps I'm on an HTC Desire running 2.2
