### ISSUE TITLE
Hubroid somewhat broken on 2.3?

### ISSUE THREAD

**Issue by ProjectMoon** [EddieRingle/hubroid#48]
I'm using Cyanogenmod 7 (Android 2.3), and Hubroid doesn't really seem to work quite right. If I tap the profile page, it goes to the profile page and then jumps back to the main menu. If I tap on Repositories it doesn't pick up any of my repos. Same for people I'm following. It does, however, pick up my news feed. Is there any reason for this oddity? Perhaps I'm just missing something...

**Comment by EddieRingle** [comment]
Ah, a fellow CM user. :)

I don't seem to have any issues like you're describing on my G2 here, but I am running the latest code from the 'next' branch (but I've never experienced such issues in previous versions, either).

**Comment by ProjectMoon** [comment]
The only thing I haven't tried is clearing the Dalvik cache. Perhaps that could fix it? I'm on an HTC Droid Incredible, if that's relevant at all.

**Comment by ProjectMoon** [comment]
I can find my repos if I search for them. However, it crashes when I try to load it. I submitted the exception through the Android issue reporter.

**Comment by ProjectMoon** [comment]
Alright, cleared cache and Dalvik cache. Still having the same issue.

**Comment by EddieRingle** [comment]
I really don't know what to tell you. I haven't seen this issue pop up for anyone else, including me. Can you possibly get me a logcat of what's happening while you try to start the Profile activity or something similar?

**Comment by markmarch** [comment]
Well I actually run into the same issue when I first run the code on my xoom. Then I turned the StrictMode off and it's gone.

**Comment by ProjectMoon** [comment]
@markmarch: How did you turn off StrictMode?

@eddieringle: I can try, yes. I also used to have Hubroid on my phone a long time ago. Maybe some old files are doing something strange to it?

**Comment by markmarch** [comment]
@ProjectMoon Change DEVELOPER_MODE to false in HubroidApplication.

**Comment by EddieRingle** [comment]
@ProjectMoon So you've compiled Hubroid yourself? In that case, @markmarch is right, StrictMode is enabled by default, but it is turned off when I publish updates to the Market. In the case of Honeycomb, some exceptions in StrictMode cause the application to crash no matter the severity. I've yet to get my hands on a Honeycomb device and do not plan on supporting tablets until a future version.

**Comment by ProjectMoon** [comment]
Have not compiled it myself yet. I currently have the market version.

**Comment by EddieRingle** [comment]
@ProjectMoon Can you please try the latest Market version and see if it helps things?

**Comment by ProjectMoon** [comment]
Tried it this morning. Same thing. I think it's my phone but I don't know what.

**Comment by ProjectMoon** [comment]
Alright, I pulled the log with Log Collector, but it's not showing anything remotely useful. Just a bunch of permission requests and processes starting up and stopping. Is there a way to turn on more detailed logging, or do I need to collect the log a different way?

**Comment by EddieRingle** [comment]
Just to be clear, 2.0 beta 3 is the latest version on the Market. If you were using 1.3.x before, you need to uninstall that version and search for Hubroid again on the Market (it's under a new package).

**Comment by ProjectMoon** [comment]
I have 2.0-beta3

**Comment by EddieRingle** [comment]
Can you send me the log?

**Comment by ProjectMoon** [comment]
So I logged out and back in and everything is fixed.  Could have swore I tried that before. Whatever.
