### ISSUE TITLE
Crash on opening private repository

### ISSUE THREAD

**Issue by pierskarsenbarg** [EddieRingle/hubroid#5]
Tried to open a private repository and the app kept suggesting that I "force close".

**Comment by EddieRingle** [comment]
I don't have any private repositories here, so can I get a link to the logcat output when it force closes?

EDIT: Wait, found what probably caused the issue and fixed it.

**Comment by EddieRingle** [comment]
Include username and API token in request to get repository info. Closed by 265c2b6ce851ff618d00159a335220748f702bbb.
