### ISSUE TITLE
Enhanced news feed

### ISSUE THREAD

**Issue by morgoth** [EddieRingle/hubroid#53]
It would be nice to have news feed similar to github web page. Short messages like "Someone did something" are not enough.
This could be some configuration option or just default behavior.
What do you think?

**Comment by EddieRingle** [comment]
Those "X did something..." messages are the result of Hubroid not recognizing what event took place. It's still beta and I haven't gotten around to fully implementing every single event type just yet, but those messages won't appear in the final release.

**Comment by morgoth** [comment]
Thx for response. Good to hear that.

**Comment by EddieRingle** [comment]
I think I've covered the most common events. Any event not fully support is backed up by 4f219a7fe342192f86428505ea399830f17aaf88, as well.
