### ISSUE TITLE
Unable to comment on issues

### ISSUE THREAD

**Issue by stwalkerster** [EddieRingle/hubroid#54]
I'm unable to comment on issues on my repo stwalkerster/eyeinthesky - it appears to allow me to comment, then when I click the "comment" button after typing in the comment, it will show the "loading" circle next to the button for about half a second, then go fullscreen with the loading circle, and then go back to the comments list. My new comment doesn't get posted at all.

**Comment by EddieRingle** [comment]
Test comment.

**Comment by EddieRingle** [comment]
@stwalkerster Appears to work, can you try again?

**Comment by stwalkerster** [comment]
no, still doesn't appear to work. Here's some photos of what happened: http://helpmebot.org.uk/wiki/Hubroid_bug

The photos are in order of what happened, every screen change I managed to get a screenshot of after a couple of attempts at commenting on this issue. I'm on a HTC Desire on Android 2.2 if that's of any help.

**Comment by stwalkerster** [comment]
Incidentally, clicking "Submit & Close" comes up with the toast "Error closing issue." too

**Comment by EddieRingle** [comment]
@stwalkerster I just tested with the Market version and was still able to post a comment. Try logging out and back in, it might be some cached authentication issue. If that doesn't work, uninstall completely and re-install and give it a go.

**Comment by stwalkerster** [comment]
test

**Comment by stwalkerster** [comment]
looks like logout/login worked, thanks!
