### ISSUE TITLE
wrong feed item titles.

### ISSUE THREAD

**Issue by badboy** [EddieRingle/hubroid#57]
I just updated to the latest market version.

The first item in my news feed should be the creation of a new repo by someone I follow (https://github.com/scy/FastTaskAsk).
I see the correct avatar but the text next to it says "agribalter commented on issue 95 on defunkt/mustache" which is 6 hours old.
Next to it is the correct "+" icon.

Clicking on this item the new title now reads "eddieringle pushed to master at eddieringle/hubroid" but the description down is "FastTaskAsk's description: ..."

It seems a little bit mixed up here, right?

**Comment by EddieRingle** [comment]
Yeah, already fixed in my local repository. I'll push a new version to the Market later today.
