### ISSUE TITLE
HTC Wildfire: startup screen doesn't scale well

### ISSUE THREAD

**Issue by nvdv** [EddieRingle/hubroid#64]
Here is example:
http://i56.tinypic.com/2qd62ip.jpg
Sorry for the quality, but I think you got the idea.

**Comment by EddieRingle** [comment]
Ah, yes. I haven't gotten a chance to create drawables for LDPI screens as
well. I'll see if I can get to that today.

**Comment by EddieRingle** [comment]
@nvdev Just pushed 20110807.01 to the Market, can you give that a try and see if everything looks alright now? :)

**Comment by nvdv** [comment]
Here's new screenshot:
http://i54.tinypic.com/r0cygg.png

**Comment by EddieRingle** [comment]
Alright, so it's more of a spacing issue, I'll take a closer look later (this time booting up an emulator to see for myself).

**Comment by EddieRingle** [comment]
@nvdev

This should be fixed as of 1c710c1430f1f1b43912c2ce13829177fb5fbd8b.

I tested in a LDPI emulator and all the icons appear to fit now. I'll try to get a release out soon.

**Comment by nvdv** [comment]
Well, everything works fine now
