### ISSUE TITLE
App logs in with email in username field

### ISSUE THREAD

**Issue by nvdv** [EddieRingle/hubroid#65]
App logs in successfully with email address in username field, but fails when I try to check my profile. I know that I should use username in this field, but I think it shouldn't work this way.

**Comment by EddieRingle** [comment]
Last time the email issue came up, it was because using an email address would crash upon login. I suppose they've fixed that on GitHub's end. I'll have to implement checks to prevent emails entirely.

Thanks for reporting this.

**Comment by EddieRingle** [comment]
Even better, I've fixed it to work even if you log in via email. :)
