### ISSUE TITLE
Compilation fails with "No resource found that matches the given name 'style/Theme.ActionBar.Light'."

### ISSUE THREAD

**Issue by progval** [EddieRingle/hubroid#67]
Hi,

I just tried to compile Hubroid, but it failed with:

```
progval@ProgVal-Andromede-Debian:~/workspace/android/hubroid$ ant debug
Buildfile: /home/progval/workspace/android/hubroid/build.xml
    [setup] Android SDK Tools Revision 12
    [setup] Project Target: Android 2.3.3
    [setup] API level: 10
    [setup] 
    [setup] ------------------
    [setup] Resolving library dependencies:
    [setup] /home/progval/workspace/android/hubroid: contrib/android-actionbar/actionbar => /home/progval/workspace/android/hubroid/contrib/android-actionbar/actionbar
    [setup] ------------------
    [setup] Ordered libraries:
    [setup] /home/progval/workspace/android/hubroid/contrib/android-actionbar/actionbar
    [setup] ------------------
    [setup] 
    [setup] WARNING: Attribute minSdkVersion in AndroidManifest.xml (7) is lower than the project target API level (10)
    [setup] 
    [setup] Importing rules file: tools/ant/main_rules.xml

-debug-obfuscation-check:

-set-debug-mode:

-compile-tested-if-test:

-pre-build:

-dirs:
     [echo] Creating output directories if needed...

-aidl:
     [echo] Compiling aidl files into Java classes...

-renderscript:
     [echo] Compiling RenderScript files into Java classes and RenderScript bytecode...

-resource-src:
     [echo] Generating R.java / Manifest.java from the resources...
     [aapt]     (skipping backup file '/home/progval/workspace/android/hubroid/res/values/styles.xml~')
     [aapt]     (skipping backup file '/home/progval/workspace/android/hubroid/res/menu/actionbar.xml~')
     [aapt] /home/progval/workspace/android/hubroid/res/values/styles.xml:3: error: Error retrieving parent for item: No resource found that matches the given name 'style/Theme.ActionBar.Light'.

BUILD FAILED
/compil/android/android-sdk-linux_x86/tools/ant/main_rules.xml:310: null returned: 1

Total time: 1 second
```

I cloned https://github.com/mhawkins/android-actionbar.git into `contrib/` (so the sources are in `contrib/android-actionbar/`).

Any idea of what I've done wrong?

Regards,
ProgVal

**Comment by EddieRingle** [comment]
1. contrib/android-actionbar is a git submodule
2. The user mhawkins has no repository named android-actionbar ;)

**Comment by progval** [comment]
mhawkins has a repository named android-actionbar: https://github.com/mhawkins/android-actionbar

However, cloning from git://github.com/johannilsson/android-actionbar.git works. Thanks. (mhawkins has a better SEO than johannilsson :/)

Thank you!

**Comment by kevonwang** [comment]
I download from https://github.com/mhawkins/android-actionbar,the new problem is coming,In net.idlesoft.android.apps.github.activities.BaseActivity,the property of ActionBar.DISPLAY_SHOW_TITLE,the functional of actionBar.setDisplayOptions,etc. is not exist.

**Comment by EddieRingle** [comment]
Did you add android-actionbar as an Android library project?

**Comment by kevonwang** [comment]
yes,I did,Maybe the versions of actionbar which hubroid needed and android-actionbar is mismatching. The class:ActionBar of android-actionbar does not have DISPLAY_SHOW_TITLE,setDisplayOptions,etc.

**Comment by JakeWharton** [comment]
1. Use [Johan Nilsson's Android-ActionBar](https://github.com/johannilsson/android-actionbar) repository and not one of the random forks from who knows when.
2. It sounds like you need the `mimic-native-api` branch.
