### ISSUE TITLE
Add oAuth support

### ISSUE THREAD

**Issue by phw** [EddieRingle/hubroid#70]
Github's API offers authentication via OAuth, but Hubroid only uses authentication by username and password.

I would prefer OAuth over the basic HTTP authentication used by Hubroid. Providing a third party App with my Github credential and storing the credentials on my mobile is a security issue.

**Comment by EddieRingle** [comment]
Agreed. I definitely want to get around to adding OAuth support also.

_Sent via Hubroid_

**Comment by EddieRingle** [comment]
Alright, I'm actively working on this. Hopefully I get something working tomorrow.

**Comment by phw** [comment]
Awesome! I should find some time to test run it once you have something running.

_Sent via Hubroid_

**Comment by EddieRingle** [comment]
@phw As you can see, I've made a commit that adds in OAuth authentication. It works well aside from private activity feeds, which only accept http basic auth. I'm talking with @kevinsawicki about this.

**Comment by EddieRingle** [comment]
Marking this as in need of an API. Once the new Events API is released and the egit-github library is updated to support it, Hubroid will be able to move over to OAuth 100%.

**Comment by EddieRingle** [comment]
The egit-github library now supports the Event API and things are in place for Hubroid to move to OAuth, will get this out the door soon. :)

**Comment by EddieRingle** [comment]
Closed by a27ce16339eac0ae0fb1affec02b99f389da8a83.

I'll have to see about cleaning up the login interface now.
