### ISSUE TITLE
optimize vertical space in the File Viewer

### ISSUE THREAD

**Issue by mturquette** [EddieRingle/hubroid#72]
When viewing a file in landscape mode (especially on a phone) there is wasted space in the horizontal bar declaring "File Viewer" and the horizontal bar below it with the name of the file currently being viewed.  Combining both of these bars into one would save lots of precious vertical space.

**Comment by EddieRingle** [comment]
Irrelevant in the 3.0 branch.

**Comment by mturquette** [comment]
Hurray.

On Thu, May 24, 2012 at 10:09 AM, Eddie Ringle
reply@reply.github.com
wrote:
