### ISSUE TITLE
Support for Android 4.0 (ICS) / Galaxy Nexus

### ISSUE THREAD

**Issue by leeola** [EddieRingle/hubroid#73]
Basically, the title says it all. When attempting to install on the Market, it says it is not compatible with the Nexus.

**Comment by EddieRingle** [comment]
Yup, definitely on my list. Waiting for ICS for my device before I do that though. (Coincidentally, that's also on me, as I appear to be one of the very few working on CM9 for the Vision)

**Comment by Maher4Ever** [comment]
This app looks soooo cool, unfortunately it's not yet supported on the GN. So +1 to this request!

**Comment by jeromelefeuvre** [comment]
+1 I want this for my touchpad ;)

**Comment by queeup** [comment]
+1 ICS support

**Comment by EddieRingle** [comment]
Just a status update; I'm currently working on what is essentially a rewrite to make things compatible with both ICS and tablets. Once I get some basic functionality in, I'll start releasing incremental updates to the Market to add features back (as well as new features, of course).

**Comment by EddieRingle** [comment]
Just pushed the rewrite branch (27ac4654480a32964a0be3af8f0e222c236c93f6) with some simple functionality. Stay tuned.

**Comment by Maher4Ever** [comment]
Great job. Thank you for working on this. I can't wait to see the result :)

**Comment by akaspin** [comment]
Bump.

**Comment by EddieRingle** [comment]
Still working on it guys. High school is finally coming to an end for me in a few days, so I'll have lots of time to work on it soon. :)
