### ISSUE TITLE
Action Bar

### ISSUE THREAD

**Issue by kevintanhongann** [EddieRingle/hubroid#77]
When I first open up the project, action bar codes ain't working properly, and some R attributes cant be resolved to their types. Perhaps that should be changed to actionbarsherlock. I'm trying to scrap out the action bar and making sure everything can be ran first, then perhaps I'll reverse engineer some functionalities in order to reproduce the action bar again.

**Comment by EddieRingle** [comment]
3.0 branch is using ActionBarSherlock.
