### ISSUE TITLE
Regarding the login screen

### ISSUE THREAD

**Issue by rikupw** [EddieRingle/hubroid#8]
You have already heard my rant.

I cannot see the login textboxes when the VK is open on my N1. 

Portrait mode, sucks, balls.
http://grenslivia.mine.nu/~riku/device.png

BTW EddieRingle, you da man.  keep up the good work :)

my suggestion:
just a single "login" button, that creates a popup with stretched out android textboxes, and use that to "login." at least until you can think of something better :)

**Comment by EddieRingle** [comment]
Made the splash scale when VK appears, now riku can stop whining. Closed by 7d74d036ecb09af65a1e6f2ae37f52b6a9ad2d20.

Signed-off-by: Eddie Ringle eddie@eringle.net
