### ISSUE TITLE
App totally broken since April 12

### ISSUE THREAD

**Issue by ccandreva** [EddieRingle/hubroid#82]
On April 12 Github shut down API V1 and V2. Since then the app does not work, and can't even log in.

**Comment by EddieRingle** [comment]
Yeah, I realize. The rewrite is coming along nicely, I just don't want to release it with so many features missing. There is also a pretty major issue I'm struggling with under the hood, so I don't know how long that'll take to fix.

**Comment by EddieRingle** [comment]
Scratch that, major issue solved. Just took a fresh look at the problem and saw my silly mistakes.

Might release an alpha build on the Play Store soon. :)
