### ISSUE TITLE
Pressing User Activity from own profile raises NoSuchMethodError

### ISSUE THREAD

**Issue by mitchellrj** [EddieRingle/hubroid#86]
net.idlesoft.android.apps.github.ui.fragments.EventsFragment.onActivityCreated ~ line 491.

NoSuchMethodError android.os.Bundle.getString

Running Android 2.3.7.

I can't figure out the reason for this error. The method seems to exist and is getting the right arguments...

**Comment by EddieRingle** [comment]
Yeah, fixed this in 6e0402200be2bb26642f0580b1de69876ea4b413, but took yesterday off so I never got around to pushing an update to the Play store. Will do so today. :)

**Comment by mitchellrj** [comment]
Great, thanks!
On Jun 18, 2012 5:52 PM, "Eddie Ringle" <
reply@reply.github.com>
wrote:
