### ISSUE TITLE
how it is possible to view source? 

### ISSUE THREAD

**Issue by bueltge** [EddieRingle/hubroid#94]
The new version is beautiful, faster and nice. Also I like it, that I can handle issues. But how it is possible to read, view source of an Repo, branch, not commits? I have read the issues for the requirement to read commits, was nice, if you can include this. 

Also miss a search for projects. 
 Thanks

**Comment by EddieRingle** [comment]
These are all things I have yet to re-implement after the rewrite. They're all on the list though.

**Comment by bueltge** [comment]
Thanks!
