### ISSUE TITLE
Crash after home screen?

### ISSUE THREAD

**Issue by jeffWelling** [EddieRingle/hubroid#95]
I just installed Hubroid and opened it but when I tap on "Events" or "Repositories" or anything else on the apps home screen, it crashes with the message "Unfortunately Android System has stopped".

Samsung Galaxy Nexus running Android 4.0.1

**Comment by EddieRingle** [comment]
Do you have the official GitHub app installed?

**Comment by jeffWelling** [comment]
Indeed I do.  Now that you mention it, it seems logical that removing the Github app would fix the problem...
Testing...

And Win Cake was had by all! (It works now)

Thanks for your help!

**Comment by jeffWelling** [comment]
It might be worth fixing the namespace collision at some point in the future, but for now, given how useless the Github Android app is, I wouldn't worry about too many people having both installed lol

**Comment by EddieRingle** [comment]
I do have the collision fixed in a refactor branch I've got going while I do some reorganization (to better prepare for a tablet layout). I don't know when that'll actually get pushed to the Play Store since the app is in a broken state locally, but we'll see soon.
